config/routes.rb
Linksquare::Application.routes.draw do
  resources :alums

end

app/models/alum.rb
class Alum < ActiveRecord::Base
  attr_accessible :city, :cohort, :expertise, :first_name, :github_link, :last_name, :linkedin_url, :picture, :state, :title, :twitter_handle
end

app/controllers/alums_controller.rb
class AlumsController < ApplicationController
  # GET /alums
  # GET /alums.json
  def index
    @alums = Alum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @alums }
    end
  end

  # GET /alums/1
  # GET /alums/1.json
  def show
    @alum = Alum.find(params[:id])

    flash[:notice] = 'Testing the flash message.'

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @alum }
    end
  end

  # GET /alums/new
  # GET /alums/new.json
  def new
    @alum = Alum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @alum }
    end
  end

  # GET /alums/1/edit
  def edit
    @alum = Alum.find(params[:id])
  end

  # POST /alums
  # POST /alums.json
  def create
    @alum = Alum.new(params[:alum])

    respond_to do |format|
      if @alum.save
        format.html { redirect_to @alum, notice: 'Alum was successfully created.' }
        format.json { render json: @alum, status: :created, location: @alum }
      else
        format.html { render action: "new" }
        format.json { render json: @alum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /alums/1
  # PUT /alums/1.json
  def update
    @alum = Alum.find(params[:id])

    respond_to do |format|
      if @alum.update_attributes(params[:alum])
        format.html { redirect_to @alum, notice: 'Alum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @alum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alums/1
  # DELETE /alums/1.json
  def destroy
    @alum = Alum.find(params[:id])
    @alum.destroy

    respond_to do |format|
      format.html { redirect_to alums_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/alums_helper.rb
module AlumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alums/_form.html.erb
<%= form_for(@alum) do |f| %>
  <% if @alum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alum.errors.count, "error") %> prohibited this alum from being saved:</h2>

      <ul>
      <% @alum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :cohort %><br />
    <%= f.text_field :cohort %>
  </div>
  <div class="field">
    <%= f.label :linkedin_url %><br />
    <%= f.text_field :linkedin_url %>
  </div>
  <div class="field">
    <%= f.label :twitter_handle %><br />
    <%= f.text_field :twitter_handle %>
  </div>
  <div class="field">
    <%= f.label :github_link %><br />
    <%= f.text_field :github_link %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :expertise %><br />
    <%= f.text_area :expertise %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alums/edit.html.erb
<h1>Editing alum</h1>

<%= render 'form' %>

<%= link_to 'Show', @alum %> |
<%= link_to 'Back', alums_path %>

app/views/alums/index.html.erb
<h1>Listing alums</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Cohort</th>
    <th>Linkedin url</th>
    <th>Twitter handle</th>
    <th>Github link</th>
    <th>City</th>
    <th>State</th>
    <th>Title</th>
    <th>Picture</th>
    <th>Expertise</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @alums.each do |alum| %>
  <tr>
    <td><%= alum.first_name %></td>
    <td><%= alum.last_name %></td>
    <td><%= alum.cohort %></td>
    <td><%= alum.linkedin_url %></td>
    <td><%= alum.twitter_handle %></td>
    <td><%= alum.github_link %></td>
    <td><%= alum.city %></td>
    <td><%= alum.state %></td>
    <td><%= alum.title %></td>
    <td><%= alum.picture %></td>
    <td><%= alum.expertise %></td>
    <td><%= link_to 'Show', alum %></td>
    <td><%= link_to 'Edit', edit_alum_path(alum) %></td>
    <td><%= link_to 'Destroy', alum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Alum', new_alum_path %>

app/views/alums/index.html.haml
%h1 Listing alums

%table
  %tr
    %th First name
    %th Last name
    %th Cohort
    %th Linkedin url
    %th Twitter handle
    %th Github link
    %th City
    %th State
    %th Title
    %th Picture
    %th Expertise
    %th 
    %th 
    %th 

  - @alums.each do |alum|
    %tr
      %td= alum.first_name 
      %td= alum.last_name 
      %td= alum.cohort 
      %td= alum.linkedin_url 
      %td= alum.twitter_handle 
      %td= alum.github_link 
      %td= alum.city 
      %td= alum.state 
      %td= alum.title 
      %td= alum.picture 
      %td= alum.expertise 
      %td= link_to 'Show', alum 
      %td= link_to 'Edit', edit_alum_path(alum) 
      %td= link_to 'Destroy', alum, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/alums/new.html.erb
<h1>New alum</h1>

<%= render 'form' %>

<%= link_to 'Back', alums_path %>

app/views/alums/show.html.haml
%p#notice=notice

%p
  %strong  First name:
  = @alum.first_name

%p
  %strong Last name:
  = @alum.last_name 


%p
  %strong Cohort:
  = @alum.cohort 


%p
  %strong Linkedin url:
  = @alum.linkedin_url 


%p
  %strong Twitter handle:
  = @alum.twitter_handle 


%p
  %strong Github link:
  = @alum.github_link 


%p
  %strong City:
  = @alum.city 


%p
  %strong State:
  = @alum.state 


%p
  %strong Title:
  = @alum.title 


%p
  %strong Picture:
  = @alum.picture 


%p
  %strong Expertise:
  = @alum.expertise 



= link_to 'Edit', edit_alum_path(@alum)  |
= link_to 'Back', alums_path 
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Linksquare</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>